[pytest]
filterwarnings =
    ignore:.*resetCache.*:DeprecationWarning
    ignore:.*enablePackrat.*:DeprecationWarning
    ignore:.*parseString.*:DeprecationWarning
    ignore:.*resetCache.*:Warning
    ignore:.*enablePackrat.*:Warning
    ignore:.*parseString.*:Warning
